- name: mounting volume to instance
  hosts: M1
  become: yes
  tasks:
  - mount:
      path: /
      src: /M1
      state: present
      fstype: ext4  
================================================================================
include_vars:
file_name: 1.yml
p_name:
    - nginx
    - tomcat9
	
- name: include_vars example
  hosts: all
  tasks:
  - name: vars include
    include_vars: 1.yml
  - name: install apache2
    apt:
      name: "{{ p_name }}"
      state: present
      update_cache: yes
================================================================================
include_tasks:
file_name: 1.yml
- name: install python3
  apt:
     name: python3
     state: present
     update_cache: yes
	 
- name: copy file
  hosts: all
  become: yes
  tasks:
  - include_tasks: play2.yml
  - copy:
      src: ~/9.yml
      dest: ~/
  - debug:
      msg: hi iam srinu from pargi

================================================================================
# ignoring_errors:

- name: example for ignore_errors
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - apt:
      name: awscli
      state: present
  - name: srinu
    service:
      name: srinu
      state: restarted
    ignore_errors: True
================================================================================
# creating a users with group,uid,shell,dir

- name: Add several users
  hosts: all
  tasks:
  - user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
      shell: "{{ item.shell }}"
      uid: "{{ item.uid }}"
      create_home: "{{ item.create_home }}"
    loop:
      - { name: 'sheshi', groups: 'ubuntu',shell: '/bin/bash',uid: '1555',create_home: 'yes' }
      - { name: 'sai', groups: 'ubuntu',shell: '/bin/bash',uid: '1556',create_home: 'yes' }
	  
=========================================================================================
- name: Test playbook for checking dictionaries
  hosts: all
  become: yes
  vars:
    dict1: 
        { name: 'srinu',uid: '1666',groups: 'ubuntu' }
    dict2:
      - { name: 'sai',uid: '1667',groups: 'ubuntu' }
      - { name: 'teju',uid: '1668',groups: 'ubuntu' }
  tasks:
  - name: creating users
    user:
    loop:
    - dict1
    - dict2
================================================================================

================================================================================