Parameters:
  sz:
    Type: Number
Resources:
  Vol:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-south-1a
      Size: 
        Ref: sz
      VolumeType: gp2
Outputs:
  volid: 
    Ref: Vol