Resources:
  SG1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription : Allow http to client host
      GroupName: sg1  
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 22
        ToPort: 22
  SG2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription : Allow http to client host
      GroupName: sg2  
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 26.90.90.90/32
        FromPort: 80
        ToPort: 80
  Vpc1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: App1-Vpc
      - Key: Env
        Value: Dev
  SN1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: 
        Ref: Vpc1
  SN2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: 
        Ref: Vpc1
  Ins1: 
    Type: AWS::EC2::Instance
    Properties: 
       SubnetId:
         Ref: SN1
       ImageId: ami-04d9e855d716f9c99
       InstanceType: t2.micro
        
Outputs:
  pvtid:
    Value: 
      Fn::GetAtt:
      - Ins1
      - PrivateIp
